# Generated by Django 5.2.5 on 2025-08-22 10:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_image_alter_listing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/demo/image/upload/placeholder.png', max_length=255, verbose_name='image'),
        ),
    ]
