# Generated by Django 5.2.5 on 2025-08-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_nextauthuser_delete_userprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nextauthuser',
            table='User',
        ),
    ]
