# Generated by Django 5.2.5 on 2025-08-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_nextauthuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nextauthuser',
            table='"User"',
        ),
    ]
